# Generated by Django 5.0.4 on 2024-04-24 19:59

import Home.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PDF_Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.CharField(max_length=1000)),
                (
                    "pdf_book",
                    models.FileField(
                        blank=True, null=True, upload_to=Home.models.Path_PDF_Book
                    ),
                ),
                ("created_dt", models.DateTimeField(auto_now_add=True)),
                (
                    "add_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
